server:
  port: 8080

spring:
  # DB Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.142:3307/test
    username: root
    password: 123456

  # redis集群
  redis:
    cluster:
      nodes:
      - 192.168.1.142:7001
      - 192.168.1.142:7002
      - 192.168.1.142:7003
      - 192.168.1.142:7004
      - 192.168.1.142:7005
      - 192.168.1.142:7006
    timeout: 5000

#  redis:
#    host: 192.168.1.142
#    database: 0
#    port: 6379
#    timeout: 1000

# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  check-config-location: true

